modules-search: [ local ]

instances:
- id: rootfs
  module:   unpackfs
  config:   unpackfs1.conf
  weight:   45

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs@rootfs
  - roman-os_kernel
  - machineid
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - fstab
  - networkcfg
  - roman-os_before
  - roman-os_remove_nvidia
  - chwd
  - initcpiocfg
  - initcpio
  - hwclock
  - services-systemd
  - roman-os_packages
  - removeuser
  - users
  - roman-os_displaymanager
  - roman-os_ucode
  - grubcfg
  - roman-os_bootloader
  - roman-os_final
  - preservefiles
  - umount
- show:
  - finished

branding: roman-os

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
