#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Calamares module that installs the live ISO's kernel into the target,
independent of which kernel package the ISO shipped (linux, linux-cachyos,
linux-zen, ...).

It detects the kernel from the live boot medium, copies the image into the
target /boot, generates a matching mkinitcpio preset, and removes the
live-only preset artifacts so the later `mkinitcpio -P` builds exactly one
correct initramfs. This replaces the old hardcoded unpackfs@vmlinuz copy and
the hardcoded preset rename in roman-os_before.
"""

import glob
import os
import shutil
import libcalamares

# Where archiso exposes the booted kernel image on the live medium.
BOOTMNT_KERNEL_GLOB = "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-*"

# Live-only mkinitcpio presets shipped in the airootfs that must not survive
# into the installed system: 'roman-os' is the old static preset, 'linux.preset'
# is the archiso live preset.
LIVE_PRESET_ARTIFACTS = ("roman-os", "linux.preset")


def detect_kernels():
    """Return [(image_path, kernel_name), ...] for every kernel on the live medium."""
    return [
        (src, os.path.basename(src)[len("vmlinuz-"):])
        for src in sorted(glob.glob(BOOTMNT_KERNEL_GLOB))
    ]


def copy_kernel_image(src, kernel, target_root):
    """Copy vmlinuz-<kernel> from the live medium into the target /boot."""
    boot_dir = os.path.join(target_root, "boot")
    os.makedirs(boot_dir, exist_ok=True)
    dst = os.path.join(boot_dir, f"vmlinuz-{kernel}")
    libcalamares.utils.debug(f"Copying kernel image {src} -> {dst}")
    shutil.copy2(src, dst)


def write_preset(kernel, target_root):
    """Generate /etc/mkinitcpio.d/<kernel>.preset with a single default image."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    os.makedirs(preset_dir, exist_ok=True)
    preset_path = os.path.join(preset_dir, f"{kernel}.preset")
    content = (
        "# mkinitcpio preset file - generated by Calamares (roman-os_kernel)\n"
        f"ALL_kver='/boot/vmlinuz-{kernel}'\n"
        "PRESETS=('default')\n"
        f'default_image="/boot/initramfs-{kernel}.img"\n'
    )
    libcalamares.utils.debug(f"Writing mkinitcpio preset {preset_path}")
    with open(preset_path, "w") as f:
        f.write(content)


def remove_live_presets(target_root):
    """Remove live-only mkinitcpio preset artifacts from the target."""
    preset_dir = os.path.join(target_root, "etc/mkinitcpio.d")
    for name in LIVE_PRESET_ARTIFACTS:
        path = os.path.join(preset_dir, name)
        if os.path.exists(path):
            libcalamares.utils.debug(f"Removing live-only preset artifact: {path}")
            os.remove(path)


def run():
    """Install the live kernel into the target, kernel-agnostically."""
    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug("Start roman-os_kernel")
    libcalamares.utils.debug("##############################################\n")

    target_root = libcalamares.globalstorage.value("rootMountPoint")

    kernels = detect_kernels()
    if not kernels:
        msg = f"No kernel image found at {BOOTMNT_KERNEL_GLOB}"
        libcalamares.utils.warning(msg)
        return ("roman-os_kernel: no kernel found", msg)

    names = [name for _, name in kernels]
    libcalamares.utils.debug(f"Detected kernel(s): {', '.join(names)}")

    try:
        # Remove the live-only presets FIRST: when the plain 'linux' kernel is one of
        # the installed kernels, write_preset() below regenerates a real linux.preset
        # that must not then be deleted as an archiso artifact.
        remove_live_presets(target_root)
        for src, name in kernels:
            copy_kernel_image(src, name, target_root)
            write_preset(name, target_root)
    except Exception as e:
        libcalamares.utils.warning(str(e))
        return ("roman-os_kernel: error", f"Failed to install kernel(s) {names}: <pre>{e}</pre>")

    # Expose for downstream modules: primary (first) for back-compat, plus the full list.
    libcalamares.globalstorage.insert("roman-osKernel", names[0])
    libcalamares.globalstorage.insert("roman-osKernels", names)

    libcalamares.utils.debug("##############################################")
    libcalamares.utils.debug(f"End roman-os_kernel - installed kernel(s): {', '.join(names)}")
    libcalamares.utils.debug("##############################################\n")
    return None
